project 'FaceSpace22.xcodeproj'
 platform :ios, '9.0'

target 'FaceSpace22' do
  pod 'Firebase/Database'
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod ‘SideMenu’
  

end
